ARG version
FROM node:${version}
RUN mkdir /app
COPY ./code/frontend /app
WORKDIR /app
RUN rm -rf /app/node_modules && \
    npm install @ionic/cli native-run cordova-res cordova-plugin-geolocation && \
    npm install @ionic/react @ionic/react-router @ionic/react-hooks @ionic/pwa-elements @ionic-native/core @ionic-native/geolocation && \
    npm install node-sass
CMD ["/app/node_modules/@ionic/cli/bin/ionic", "serve"]