ARG version
FROM node:${version}
RUN mkdir /app
COPY ./code/frontend /app
WORKDIR /app
RUN rm -R /app/node_modules && \
    npm install @ionic/cli native-run cordova-res && \
    npm install @ionic/react @ionic/react-router @ionic/react-hooks @ionic/pwa-elements
CMD ["/app/node_modules/@ionic/cli/bin/ionic", "serve"]