ARG version
FROM node:${version}
RUN mkdir /app
COPY ./code/frontend /app
WORKDIR /app
RUN rm -rf /app/node_modules && \
    npm install @ionic/cli native-run cordova-res cordova-plugin-geolocation && \
    npm install @ionic/react @ionic/react-router @ionic/react-hooks @ionic/pwa-elements @ionic-native/core @ionic-native/geolocation && \
    npm install node-sass && \
    npm install d3 @types/d3-selection @types/d3-scale @types/d3-array @types/d3-axis @types/d3-shape @types/d3-zoom @types/d3-interpolate @types/d3-color @types/d3-geo @types/d3-transition @types/d3-path && \
    npm install @react-google-maps/api