version: "3.7"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
      args:
        - version=${BACKEND_PYTHON_VERSION}
    restart: on-failure
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "${BACKEND_DJANGO_PORT}:${BACKEND_DJANGO_DEFAULT_PORT}"
    volumes:
      - ./backend/code:/app
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0:${BACKEND_DJANGO_DEFAULT_PORT}"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      args:
        - version=${FRONTEND_NODE_VERSION}
    restart: on-failure
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_DEFAULT_PORT}"
    volumes:
      - ./frontend/code/frontend:/app
    command: >
      sh -c "ionic serve"
    depends_on:
      - backend
