version: "3.7"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
      args:
        - version=${BACKEND_PYTHON_VERSION}
    restart: always
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "${BACKEND_DJANGO_PORT}:${BACKEND_DJANGO_DEFAULT_PORT}"
    volumes:
      - ./backend/code:/app
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0:${BACKEND_DJANGO_DEFAULT_PORT}"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      args:
        - version=${FRONTEND_NODE_VERSION}
    restart: always
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_DEFAULT_PORT}"
    volumes:
      - ./frontend/code/frontend/src:/app/src
      - ./frontend/code/frontend/public:/app/public
      - ./frontend/code/frontend/.gitignore:/app/.gitignore
      - ./frontend/code/frontend/capacitor.config.json:/app/capacitor.config.json
      - ./frontend/code/frontend/ionic.config.json:/app/ionic.config.json
      - ./frontend/code/frontend/package.json:/app/package.json
      - ./frontend/code/frontend/package-lock.json:/app/package-lock.json
      - ./frontend/code/frontend/tsconfig.json:/app/tsconfig.json
    depends_on:
      - backend
